### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [thedillonb/CodeHub-Push#1]
this query looks wrong:

``` js
.none('select * from records where token=$1 and oauth=$2', [token, auth])
```

you execute `SELECT` via `none`, meaning the query isn't supposed to return anything. Doesn't look right;)

**Comment by thedillonb** [comment]
Great catch. I can't even believe I accidentally pushed that stuff to master instead of a dev branch. That work is not even done yet :open_mouth:

**Comment by thedillonb** [comment]
This has been corrected in `master`.
