### ISSUE TITLE
No more notifications in CodeHub

### ISSUE THREAD

**Issue by RonnieRocket147** [thedillonb/CodeHub-Push#4]
Since a couple of weeks push notifications have stopped in CodeHub iOS app. I have a Pro upgrade.

Any known issue?

**Comment by thedillonb** [comment]
Typically, notification availability will be filed as an Issue under the thedillonb/CodeHub repository. Unfortunately, I didn't see this issue. However, I believe your issue has been solved since then as others communicated the failure as well.
